import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    justifyContent: 'space-between',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  headerTitle: {
    color: colors.textPrimary,
    fontSize: 17,
    fontWeight: '600',
  },
metaRow: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  paddingHorizontal: 16,
  paddingTop: 12,
  paddingBottom: 8,
  gap: 10,
},
  metaChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#16281C',
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  metaText: {
    color: colors.textSecondary,
    fontSize: 12,
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 8,
    flex: 1,
  },
  formCard: {
    backgroundColor: '#101F16',
    borderWidth: 1,
    borderColor: '#1E3327',
    borderRadius: 14,
    padding: 14,
  },
  label: {
    color: colors.textSecondary,
    fontSize: 13,
    marginBottom: 8,
    marginTop: 16,
  },
  textArea: {
    backgroundColor: colors.inputBackground,
    borderRadius: 10,
    padding: 14,
    minHeight: 110,
    fontSize: 14,
    color: colors.inputText,
    textAlignVertical: 'top',
  },
  mediaRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 12,
  },
  mediaButton: {
    flex: 1,
    backgroundColor: '#0B1C13',
    borderWidth: 1,
    borderColor: '#1A3324',
    borderRadius: 10,
    paddingVertical: 10,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
  },
  mediaButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '400',
  },
  previewRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#16281C',
    borderRadius: 10,
    padding: 8,
    marginBottom: 8,
  },
  previewThumb: {
    width: 44,
    height: 44,
    borderRadius: 8,
    backgroundColor: '#2A4A36',
    justifyContent: 'center',
    alignItems: 'center',
  },
  previewInfo: {
    flex: 1,
  },
  previewName: {
    color: '#FFFFFF',
    fontSize: 12,
  },
  previewMeta: {
    color: '#7C8880',
    fontSize: 11,
    marginTop: 2,
  },
  audioPlayIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#2A4A36',
    justifyContent: 'center',
    alignItems: 'center',
  },
  waveform: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    height: 20,
  },
  waveformBar: {
    width: 2,
    backgroundColor: '#3E6A4F',
    borderRadius: 1,
  },
  saveButton: {
    backgroundColor: colors.accent,
    marginHorizontal: 16,
    marginBottom: 20,
    paddingVertical: 15,
    borderRadius: 10,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
  },
  saveButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '500',
  },
});