import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';

// cor específica deste componente — não se repete em nenhuma outra tela do app
const waveformBar = '#3E6A4F';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    justifyContent: 'space-between',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  headerTitle: {
    color: colors.textPrimary,
    fontSize: 17,
    fontWeight: '600',
  },
  metaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 8,
    gap: 10,
  },
  metaChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: colors.surfaceAlt,
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  metaText: {
    color: colors.textSecondary,
    fontSize: 12,
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 20,
    flexGrow: 1,
  },
  formCard: {
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.borderAlt,
    borderRadius: 14,
    padding: 14,
  },
  label: {
    color: colors.textSecondary,
    fontSize: 13,
    marginBottom: 8,
    marginTop: 16,
  },
  labelFirst: {
    color: colors.textSecondary,
    fontSize: 13,
    marginBottom: 8,
  },
  input: {
    backgroundColor: colors.inputBackground,
    borderRadius: 10,
    paddingHorizontal: 12,
    minHeight: 48,
    fontSize: 14,
    color: colors.inputText,
  },
  selectInput: {
    backgroundColor: colors.inputBackground,
    borderRadius: 10,
    paddingHorizontal: 12,
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  selectPlaceholder: {
    color: colors.placeholder,
    fontSize: 14,
  },
  selectValue: {
    color: colors.inputText,
    fontSize: 14,
  },
  optionsList: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: 10,
    marginTop: 6,
    overflow: 'hidden',
  },
  option: {
    paddingHorizontal: 12,
    paddingVertical: 11,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderAlt,
  },
  optionText: {
    color: colors.textPrimary,
    fontSize: 14,
  },
  textArea: {
    backgroundColor: colors.inputBackground,
    borderRadius: 10,
    padding: 12,
    minHeight: 110,
    fontSize: 14,
    color: colors.inputText,
    textAlignVertical: 'top',
  },
  mediaRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 12,
  },
  mediaButton: {
    flex: 1,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.borderAlt,
    borderRadius: 10,
    paddingVertical: 10,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
  },
  mediaButtonText: {
    color: colors.onAccent,
    fontSize: 13,
    fontWeight: '400',
  },
  mediaError: {
    color: colors.danger,
    fontSize: 12,
    marginBottom: 12,
  },
  previewRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: colors.surfaceAlt,
    borderRadius: 10,
    padding: 8,
    marginBottom: 8,
  },
  previewThumb: {
    width: 44,
    height: 44,
    borderRadius: 8,
    backgroundColor: colors.borderAlt,
    justifyContent: 'center',
    alignItems: 'center',
  },
  previewImage: {
    width: 44,
    height: 44,
    borderRadius: 8,
  },
  previewInfo: {
    flex: 1,
  },
  previewName: {
    color: colors.onAccent,
    fontSize: 12,
  },
  previewMeta: {
    color: colors.textSecondary,
    fontSize: 11,
    marginTop: 2,
  },
  audioPlayIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.borderAlt,
    justifyContent: 'center',
    alignItems: 'center',
  },
  waveform: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    height: 20,
  },
  waveformBar: {
    width: 2,
    backgroundColor: waveformBar,
    borderRadius: 1,
  },
  saveButton: {
    backgroundColor: colors.accent,
    marginHorizontal: 16,
    marginBottom: 20,
    paddingVertical: 15,
    borderRadius: 10,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
  },
  saveButtonText: {
    color: colors.onAccent,
    fontSize: 15,
    fontWeight: '500',
  },
});